### ISSUE TITLE
plist issue with p5-Net-APNS-Persistent

### ISSUE THREAD

**Issue by macfat** [cullum/freebsd-ports#1]
Hi,
First line in freebsd-ports/net/p5-Net-APNS-Persistent/pkg-plist makes the installation crash - might want to remove it ;-)

also dovecot port revision is bumped to _2 now

Best Regards
René

**Comment by cullum** [comment]
Fixed by 49ebb559a461c71784f6e6d353fb5388904684e6 and 77d447ba6945b0eba4c83ab49e4807dca0973955 .

Thanks!
