### ISSUE TITLE
Any chance for getting Dovecot Push Notifications into official ports?

### ISSUE THREAD

**Issue by hoeni** [cullum/freebsd-ports#2]
Hi,

while trying to take a test ride with Dovecot Push Notifications, I fell into dependency hell in my ansible-managed PKG-only jail, because the port versions of various stuff collided with the port-available versions and so on (not your fault, it's always like this when mixing up pkg and ports). Finally decided not take the risk of ruining a well running system (lazy me ;-) ).

Is there any chance, these dovecot patches and the related additional ports will appear in the official ports some day?

Best regards from a sunny Munich, Germany, Tobi

**Comment by cullum** [comment]
Thanks for reaching out! I considered submitting this patch to the ports tree, but I'm not sure the maintainers would want to deal with it. The patchset requires a fair amount of manual changes to make it work with each new dovecot release.

Also, Apple has recently announced that they are dropping Mail server support from OSX Server this fall, so the certificate-trick will probably quit working as soon as your original one expires. :( I need to update the readme with that info.

https://support.apple.com/en-us/HT208312

**Comment by hoeni** [comment]
Oh, thanks for your reply.
What a pity that this possibility will be gone in the future :-(
With that in mind, it will not make sense to introduce patches to the normal ports tree, of course.
Thanks for your efforts anyway!

Tobi
